"""Train and export a very small C++ decision tree for the M5."""
import json
from pathlib import Path

import numpy as np
from sklearn.tree import DecisionTreeClassifier

from train_baseline import LABELS, load_clean_trials, make_windows


def cpp_node(tree, node=0, indent='  '):
    feature = int(tree.feature[node])
    if feature < 0:
        values = tree.value[node][0]
        return indent + f'return {int(np.argmax(values))};\n'
    threshold = float(tree.threshold[node])
    left = int(tree.children_left[node])
    right = int(tree.children_right[node])
    text = indent + f'if (features[{feature}] <= {threshold:.9g}f) {{\n'
    text += cpp_node(tree, left, indent + '  ')
    text += indent + '} else {\n'
    text += cpp_node(tree, right, indent + '  ')
    text += indent + '}\n'
    return text


def main():
    data = Path(__file__).parent / 'data'
    out = Path(__file__).parent / 'model'
    trials = load_clean_trials(data)
    x, y, groups = make_windows(trials)
    model = DecisionTreeClassifier(max_depth=2, min_samples_leaf=2, random_state=7)
    model.fit(x, y)
    labels = [str(label) for label in model.classes_]
    header = '''#pragma once
// Generated by export_embedded.py. Features must match train_baseline.py.
// 48 floats: 8 signals (6 axes + accel magnitude + gyro magnitude) x
// mean, standard deviation, minimum, maximum, RMS, mean absolute difference.
namespace tinyml_motion {
inline int predict(const float* features) {
'''
    header += cpp_node(model.tree_)
    header += '}\n'
    header += 'inline const char* label(int id) {\n  switch (id) {\n'
    for i, label in enumerate(labels):
        header += f'    case {i}: return "{label}";\n'
    header += '    default: return "UNKNOWN";\n  }\n}\n}\n'
    out.mkdir(exist_ok=True)
    (out / 'motion_tree.h').write_text(header, encoding='utf-8')
    metrics = {
        'model': 'DecisionTreeClassifier', 'max_depth': 2,
        'nodes': int(model.tree_.node_count), 'leaves': int(model.get_n_leaves()),
        'feature_count': int(x.shape[1]), 'training_windows': int(len(x)),
        'training_trials': sorted(set(groups)), 'classes': labels,
        'note': 'Final tree trained on all clean trials; evaluate before claiming general accuracy.'
    }
    (out / 'embedded_model.json').write_text(json.dumps(metrics, indent=2), encoding='utf-8')
    print(json.dumps(metrics, indent=2))


if __name__ == '__main__':
    main()
